target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
   pod 'AppCenter'
   pod 'AppCenter/Analytics'
   pod 'AppCenter/Crashes'
   pod 'AppCenter/Distribute'
  pod 'shared', :path => '../shared'
end