# This is a basic workflow to help you get started with Actions

name: CI - Android App Center deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # will not run the action on specified files, so when updating readmes...
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # set the runner - os that will be used to run the commands, check github actions for more OSes
    #runs-on: macos-latest
    runs-on: ubuntu-latest
    
    # set the working directory - we dont have project in git root dir but inside KotlinMMP
    env:
      working-directory: ./KotlinMMP
      
    steps:
    # USES - uses alredy pre-defined github actions so they can be reused across other repos
    # checkout our branch into the runner (OS)  or @v2 or @master
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      
      # setup JAVA verssion - check github what other version are available
      with:
       java-version: '11'

    - name: Check the code with the LINTer
      # run: ./gradlew lint
      run: ls
      working-directory: ${{env.working-directory}}

#     - name: emulator-5554 error - Remove ndk-bundle folder, Create .android folder, Create cfg file
#       # this makes it point to the correct ndk folder
#       run: rm -rf /usr/local/lib/android/sdk/ndk-bundle && mkdir ~/.android && touch ~/.android/repositories.cfg
#       working-directory: ${{env.working-directory}}

#     - name: Unit tests
#       run: ./gradlew test
#       working-directory: ${{env.working-directory}}

#     - name: emulator-5554 error - run sdkmanager
#       # below line works but when sdkmanager path is run as \sdkmanager in Platform tests below by ./gradlew connectedCheck script creates error
#       run: /usr/bin/sh -c /usr/local/lib/android/sdk/tools/bin/sdkmanager --install 'system-images;android-30;default;x86' --channel=0 > /dev/null
#       working-directory: ${{env.working-directory}}

#     - name: emulator-5554 error - list available adb devices
#       run: /usr/local/lib/android/sdk/platform-tools/adb devices
#       working-directory: ${{env.working-directory}}

    - name: Platform tests
      # run: /usr/bin/sh -c /usr/local/lib/android/sdk/tools/bin/sdkmanager --install 'system-images;android-30;default;x86' --channel=0 > /dev/null
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck
       
    # builds APK  
    - name: build release package  (APK)
      run: ./gradlew assembleRelease -PstorePw=${{secrets.ANDROID_KEY_STORE_PASSWORD}} -PkeyPw=${{secrets.ANDROID_KEY_PASSWORD}}
      working-directory: ${{env.working-directory}}

      
    # builds AAB bundle
    # default path (not MMP)    app/build/outputs/bundle/release
    - name: build release bundle (AAB)
      run: ./gradlew bundleRelease -PstorePw=${{secrets.ANDROID_KEY_STORE_PASSWORD}} -PkeyPw=${{secrets.ANDROID_KEY_PASSWORD}}
      working-directory: ${{env.working-directory}}
      
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: AND-Digital-Jemison/The-Mobile-App-android
        token: ${{secrets.APP_CENTER_KEY}}
        group: Collaborators
        file: ${{env.working-directory}}/androidApp/build/outputs/apk/release/androidApp-release.apk
        notifyTesters: true
        debug: true
    
