name: CI - iOS App Center deployment

on:
  push:
    branches: [ios-Github-Actions]
    paths-ignore:
      - "**.md"

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    env:
      working-directory: KotlinMMP
      
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
     
    - name: Force xcode 13
      run: sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer
      
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '16'

    - name: gradle version
      run: gradle -v

    - uses: yukiarrr/ios-build-action@v1.4.0
      with:
        project-path: ${{env.working-directory}}/iosApp/iosApp.xcodeproj
        p12-base64: ${{ secrets.P12_CER_BASE64 }}
        mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
        team-id: ${{ secrets.TEAM_ID }}
        workspace-path: ${{env.working-directory}}/iosApp/iosApp.xcworkspace 
        certificate-password: ${{ secrets.CERT_PASSWORD }}
        export-method: development
        output-path: iosApp.ipa

    - uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: iosApp.ipa

  upload-app-center:
    runs-on: ubuntu-latest
    needs: [build]
      
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: release-apk
    
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: AND-Digital-Jemison/The-Mobile-App-iOS
        token: ${{secrets.APP_CENTER_KEY_IOS}}
        group: Collaborators;Testers
        file: iosApp.ipa
        notifyTesters: true
        debug: true
