name: CI - Android App Center deployment

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./KotlinMMP
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '11'

    - name: Check the code with the LINTer
      run: ./gradlew lint
      working-directory: ${{env.working-directory}}

    - name: Unit tests
      run: ./gradlew test
      working-directory: ${{env.working-directory}}

  test:
    runs-on: macos-latest
    needs: build
    env:
      working-directory: ./KotlinMMP
    steps:
    - uses: actions/checkout@v2
    - name: Platform tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck
        working-directory: ${{env.working-directory}}
       
  final-build-upload:
    runs-on: ubuntu-latest
    needs: test
    env:
      working-directory: ./KotlinMMP
    # builds APK 
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '11'
    - name: build release package  (APK)
      run: ./gradlew assembleRelease -PstorePw=${{secrets.ANDROID_KEY_STORE_PASSWORD}} -PkeyPw=${{secrets.ANDROID_KEY_PASSWORD}}
      working-directory: ${{env.working-directory}}

      
    # builds AAB bundle
    # default path (not MMP)    app/build/outputs/bundle/release
    - name: build release bundle (AAB)
      run: ./gradlew bundleRelease -PstorePw=${{secrets.ANDROID_KEY_STORE_PASSWORD}} -PkeyPw=${{secrets.ANDROID_KEY_PASSWORD}}
      working-directory: ${{env.working-directory}}
      
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: AND-Digital-Jemison/The-Mobile-App-android
        token: ${{secrets.APP_CENTER_KEY}}
        group: Collaborators
        file: ${{env.working-directory}}/androidApp/build/outputs/apk/release/androidApp-release.apk
        notifyTesters: true
        debug: true
    
