name: CI - Android App Center deployment

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      
  workflow_dispatch:
  
env:
  working-directory: ./KotlinMMP

jobs:
  linting:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '11'

    - name: Check the code with the LINTer
      run: ./gradlew lint
      working-directory: ${{env.working-directory}}

  unit-tests:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '11'

    - name: Unit tests
      run: ./gradlew test
      working-directory: ${{env.working-directory}}

  ui-tests:
    runs-on: macos-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '11'
       
    - name: Emulator tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck
        working-directory: ${{env.working-directory}}
       
  build-package:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '11'
       
    - name: build release package  (APK)
      run: ./gradlew assembleRelease -PstorePw=${{secrets.ANDROID_KEY_STORE_PASSWORD}} -PkeyPw=${{secrets.ANDROID_KEY_PASSWORD}}
      working-directory: ${{env.working-directory}}
    
    - name: build release bundle (AAB)
      run: ./gradlew bundleRelease -PstorePw=${{secrets.ANDROID_KEY_STORE_PASSWORD}} -PkeyPw=${{secrets.ANDROID_KEY_PASSWORD}}
      working-directory: ${{env.working-directory}}
      
    - uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: ${{env.working-directory}}/androidApp/build/outputs/apk/release/androidApp-release.apk
        
  upload-app-center:
    runs-on: ubuntu-latest
    needs: [build-package, unit-tests, ui-tests, linting]
      
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: release-apk
    
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: AND-Digital-Jemison/The-Mobile-App-android
        token: ${{secrets.APP_CENTER_KEY}}
        group: Collaborators
        file: ${{env.working-directory}}/androidApp/build/outputs/apk/release/androidApp-release.apk
        notifyTesters: true
        debug: true
    
