name: Deployment Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      
  workflow_dispatch:
  
env:
  working-directory: ./KotlinMMP

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '11'

    - name: Check the code with the LINTer
      run: ./gradlew lint
      working-directory: ${{env.working-directory}}

  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '11'

    - name: Unit tests
      run: ./gradlew test
      working-directory: ${{env.working-directory}}

  android-ui-tests:
    runs-on: macos-latest
      
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '11'

    - name: Emulator tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck
        disable-animations: true
        working-directory: ${{env.working-directory}}
        profile: pixel

  android-build-package:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '11'

    - name: Save env_name
      run: |
        echo "BRANCH_NAME=${{ github.head_ref }}" > env.txt
        cat env.txt

    - name: Commit env file
      uses: EndBug/add-and-commit@v7
      with:
        add: './env.txt'
        message: added env file
        push: false

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
          force: true

    - name: Install AWS CLI & Configuring Profile Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
        aws configure set default.region eu-west-1

    - name: Install Amplify CLI & Deploying Project
      run: |
        npm install -g @aws-amplify/cli --unsafe-perm=true
        bash amplify-init-android.sh
        amplify push --yes
      working-directory: ${{env.working-directory}}/androidApp

    - name: Commit Amplify Files
      uses: EndBug/add-and-commit@v7
      with:
        add: '["./KotlinMMP/androidApp/src/main/res/raw/amplifyconfiguration.json","./KotlinMMP/androidApp/src/main/res/raw/awsconfiguration.json"]'
        message: Apply automatic changes
        push: false

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
        force: true


    - name: build release package  (APK)
      run: ./gradlew assembleRelease -PstorePw=${{secrets.ANDROID_KEY_STORE_PASSWORD}} -PkeyPw=${{secrets.ANDROID_KEY_PASSWORD}}
      working-directory: ${{env.working-directory}}

    - name: build release bundle (AAB)
      run: ./gradlew bundleRelease -PstorePw=${{secrets.ANDROID_KEY_STORE_PASSWORD}} -PkeyPw=${{secrets.ANDROID_KEY_PASSWORD}}
      working-directory: ${{env.working-directory}}

    - uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: ${{env.working-directory}}/androidApp/build/outputs/apk/release/androidApp-release.apk

  ios-ui-tests:
    runs-on: 	macos-11

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '11'
       
    - name: Force xcode 13
      run: sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer

    - name: Emulator tests
      run: xcodebuild -workspace iosApp.xcworkspace -scheme iosApp -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 13' clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      working-directory: ${{env.working-directory}}/iosApp
      
  ios-build-package:
    runs-on: macos-11

    env:
      working-directory: KotlinMMP
      
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
     
    - name: Force xcode 13
      run: sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer

    - name: Save env_name
      run: |
          echo "BRANCH_NAME=${{ github.head_ref }}" > env.txt
          cat env.txt

    - name: Commit env file
      uses: EndBug/add-and-commit@v7
      with:
        add: './env.txt'
        message: added env file

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
        force: true

    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '16'

    - name: Install AWS CLI & Configuring Profile Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
        sudo installer -pkg ./AWSCLIV2.pkg -target /
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
        aws configure set default.region eu-west-1

    - name: Install Amplify CLI & Deploying Project
      run: |
        npm install -g @aws-amplify/cli --unsafe-perm=true
        bash amplify-init-ios.sh
        amplify push --yes
      working-directory: ${{env.working-directory}}/iosApp

    - name: Commit Amplify Files
      uses: EndBug/add-and-commit@v7
      with:
        add: '["./KotlinMMP/iosApp/amplifyconfiguration.json","./KotlinMMP/iosApp/awsconfiguration.json"]'
        message: Apply automatic changes
        push: false

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
        force: true

    - name: gradle version
      run: gradle -v

    - uses: yukiarrr/ios-build-action@v1.4.0
      with:
        project-path: ${{env.working-directory}}/iosApp/iosApp.xcodeproj
        p12-base64: ${{ secrets.P12_CER_BASE64 }}
        mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
        team-id: ${{ secrets.TEAM_ID }}
        workspace-path: ${{env.working-directory}}/iosApp/iosApp.xcworkspace 
        certificate-password: ${{ secrets.CERT_PASSWORD }}
        export-method: development
        output-path: iosApp.ipa

    - uses: actions/upload-artifact@v2
      with:
        name: release-ipa
        path: iosApp.ipa

  ios-upload-app-center:
    runs-on: ubuntu-latest
    needs: [linting, unit-tests, android-ui-tests, android-build-package, ios-ui-tests, ios-build-package]
      
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: release-ipa
    
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: AND-Digital-Jemison/The-Mobile-App-iOS
        token: ${{secrets.APP_CENTER_KEY_IOS}}
        group: Collaborators
        file: iosApp.ipa
        notifyTesters: true
        debug: true

  android-upload-app-center:
    runs-on: ubuntu-latest
    needs: [linting, unit-tests, android-ui-tests, android-build-package, ios-ui-tests, ios-build-package]

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: release-apk

    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: AND-Digital-Jemison/The-Mobile-App-android
        token: ${{secrets.APP_CENTER_KEY}}
        group: Collaborators
        file: androidApp-release.apk
        notifyTesters: true
        debug: true

  push-to-prod:
    runs-on: ubuntu-latest
    needs: [android-upload-app-center, ios-upload-app-center]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        persist-credentials: false 
        fetch-depth: 0 
        
    - name: Save env_name
      run: |
          echo "BRANCH_NAME=prod" > env.txt
          cat env.txt

    - name: Commit env file
      uses: EndBug/add-and-commit@v7
      with:
        message: added env file
        push: false

        
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: prod
        force: true
    
