# This is a basic workflow to help you get started with Actions

name: CI - Android / iOS build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      working-directory: ./KotlinMMP
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '11'
    
    - name: see the ls of root
      run: ls
      
    - name: see the ls of kotlinMMP
      run: ls KotlinMMP
    
    #- name: Make gradlew executable
     # run: chmod +x gradlew
    - name: Builds gradle wrapper file
      run: ./gradle wrapper
      working-directory: ${{env.working-directory}}
      
    - name: Tests the project
      run: ./gradlew test
      working-directory: ${{env.working-directory}}
      
    - name: Build the project
      run: ./gradlew assemble
      working-directory: ${{env.working-directory}}
