name: Pull request Testing

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      
  workflow_dispatch:
  
env:
  working-directory: ./KotlinMMP

jobs:
  linting:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '11'

    - name: Check the code with the LINTer
      run: ./gradlew lint
      working-directory: ${{env.working-directory}}

  unit-tests:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '11'

    - name: Unit tests
      run: ./gradlew test
      working-directory: ${{env.working-directory}}

#  android-build:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Save env_name
#      run: |
#        echo "BRANCH_NAME=${{ github.head_ref }}" > env.txt
#        cat env.txt

#    - name: Commit env file
#      uses: EndBug/add-and-commit@v7
#      with:
#        message: added env file


  android-ui-tests:
    runs-on: macos-latest
    steps:
    - name: gradle-version
      run: gradle -v
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '11'

    - name: Save env_name
      run: |
        echo "BRANCH_NAME=${{ github.head_ref }}" > env.txt
        cat env.txt

    - name: Commit env file
      uses: EndBug/add-and-commit@v7
      with:
        message: added env file

    - name: Install AWS CLI & Configuring Profile Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
        sudo installer -pkg ./AWSCLIV2.pkg -target /
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
        aws configure set default.region eu-west-1

    - name: Install Amplify CLI & Deploying Project
      run: |
        npm install -g @aws-amplify/cli --unsafe-perm=true
        bash amplify-init-android.sh
        amplify push --yes
      working-directory: ${{env.working-directory}}/androidApp

    - name: Commit Amplify Files
      uses: EndBug/add-and-commit@v7
      with:
        add: '["./KotlinMMP/androidApp/src/main/res/raw/amplifyconfiguration.json","./KotlinMMP/androidApp/src/main/res/raw/awsconfiguration.json"]'
        message: Apply automatic changes


    - name: Emulator tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck
        disable-animations: true
        working-directory: ${{env.working-directory}}
        profile: pixel

  ios-ui-tests:
    runs-on: 	macos-11
      
    steps:
    - name: gradle-version
      run: gradle -v
      
    - name: macos-version
      run: sw_vers
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
       java-version: '11'
       
    - name: Force xcode 13
      run: sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer

    - name: Save env_name
      run: |
        echo "BRANCH_NAME=${{ github.head_ref }}" > env.txt
        cat env.txt

    - name: Commit env file
      uses: EndBug/add-and-commit@v7
      with:
        message: added env file

    - name: Install AWS CLI & Configuring Profile Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
        sudo installer -pkg ./AWSCLIV2.pkg -target /
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
        aws configure set default.region eu-west-1

    - name: Install Amplify CLI & Deploying Project
      run: |
        npm install -g @aws-amplify/cli --unsafe-perm=true
        bash amplify-init-ios.sh
        amplify push --yes
      working-directory: ${{env.working-directory}}/iosApp

    - name: Commit Amplify Files
      uses: EndBug/add-and-commit@v7
      with:
        add: '["./KotlinMMP/iosdApp/amplifyconfiguration.json","./KotlinMMP/iosApp/awsconfiguration.json"]'
        message: Apply automatic changes

    - name: Emulator tests
      run: xcodebuild -workspace iosApp.xcworkspace -scheme iosApp -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 13' clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      working-directory: ${{env.working-directory}}/iosApp

