name: Pull request Testing

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"

  workflow_dispatch:

env:
  working-directory: ./KotlinMMP
  SCHEME: "iosApp"
  DEVICE: "iPhone 13"
  DERIVED_DATA_PATH: "DerivedData"
  UI_TEST_TARGET: "iosAppUITests"
  UNIT_TEST_TARGET: "iosAppTests"
jobs:
  # linting:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup Java JDK
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: "11"

  #     - name: Check the code with the LINTer
  #       run: ./gradlew lint
  #       working-directory: ${{env.working-directory}}

  # unit-tests:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup Java JDK
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: "11"

  #     - name: Unit tests
  #       run: ./gradlew test
  #       working-directory: ${{env.working-directory}}

  # android-ui-tests:
  #   runs-on: macos-latest

  #   steps:
  #     - name: gradle-version
  #       run: gradle -v
  #     - uses: actions/checkout@v2
  #     - name: Setup Java JDK
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: "11"

  #     - name: Emulator tests
  #       uses: reactivecircus/android-emulator-runner@v2
  #       with:
  #         api-level: 29
  #         script: ./gradlew connectedCheck
  #         disable-animations: true
  #         working-directory: ${{env.working-directory}}

  build:
    name: Build
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: macos-version
      run: sw_vers
    - name: Force xcode 13
      run: sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer
       
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
        java-version: "11"
    - name: Build application
      run: |
        set -o pipefail && xcodebuild clean -workspace iosApp.xcworkspace -scheme $SCHEME -destination "platform=iOS Simulator,OS=15.0,name=iPhone 13" -derivedDataPath $DERIVED_DATA_PATH build-for-testing | xcpretty --color --simple
      working-directory: ${{env.working-directory}}/iosApp
    - name: Upload products
      uses: actions/upload-artifact@v1
      with:
        name: Products
        path:  ${{env.working-directory}}/iosApp/DerivedData/Build/Products

#   unit_test:
#     name: Unit test
#     runs-on: macOS-latest
#     needs: build
#     steps:
#     - name: Checkout project
#       uses: actions/checkout@v1
#     - name: Download products
#       uses: actions/download-artifact@v1
#       with:
#         name: Products
#     - name: Run unit tests
#       run: |
#         set -o pipefail && xcodebuild test-without-building -xctestrun $(find . -type f -name "*.xctestrun") -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 13' -derivedDataPath $DERIVED_DATA_PATH -enableCodeCoverage YES -only-testing:$UNIT_TEST_TARGET | xcpretty --color --simple
#     - name: Upload test logs
#       uses: actions/upload-artifact@v1
#       with:
#         name: TestLogs
#         path: DerivedData/Logs/Test

  ui_test:
    name: UI test
    runs-on: macos-11
    needs: build
    steps:
    - name: Checkout project 
      uses: actions/checkout@v1
    - name: Download products
      uses: actions/download-artifact@v1
      with:
        name: Products
        path: ${{env.working-directory}}/iosApp
    - name: macos-version
      run: sw_vers
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
        java-version: "11"
    - name: Force xcode 13
      run: sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer
    
    - run: find . -type f -name "*.xctestrun"
    - name: Run UI tests
      run: |
        set -o pipefail && xcodebuild test-without-building -xctestrun $(find . -type f -name "*.xctestrun") -destination "platform=iOS Simulator,OS=15.0,name=iPhone 13" -derivedDataPath $DERIVED_DATA_PATH -enableCodeCoverage YES -only-testing:iosAppUITests | xcpretty  --color --simple
      working-directory: ${{env.working-directory}}/iosApp   
#   ios-ui-tests:
#     runs-on: macos-11

#     steps:
#       - name: gradle-version
#         run: gradle -v

#       - name: macos-version
#         run: sw_vers
#       - uses: actions/checkout@v2
#         with:
#           ref: ${{ github.head_ref }}
#       - name: Setup Java JDK
#         uses: actions/setup-java@v1
#         with:
#           java-version: "11"

#       - name: Force xcode 13
#         run: sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer

#       - name: Emulator tests
#         run: sh ./ios-build.sh
#         working-directory: ${{env.working-directory}}/iosApp

#       - name: TESTING OUTPUT
#         run: find . -type f -name '/Users/runner/Library/Developer/Xcode/DerivedData/iosApp-*/Logs/Test/*.xcresult.sh' -exec cat {} \;
